In [ ]:
#Q1) Reverse the NumPy array: arr = np.array([1, 2, 3, 6, 4, 5])
import numpy as np
arr = np.array([1,2,3,6,4,5])
arrs = np.array(arr[:: -1 ])
print(arrs)

[5 4 6 3 2 1]


In [ ]:
#Q3) Find the most frequent value and their indice(s) in the following arrays:
#  i. x = np.array([1,2,3,4,5,1,2,1,1,1])

import numpy as np

x = np.array([1, 2, 3, 4, 5, 1, 2, 1, 1, 1])

frequent_value1 = np.bincount(x).argmax()

index1 = np.where(x == frequent_value1)[0]

print("The most frequent value in the array is: ", frequent_value1)

print("The indices of the most frequent value:", index1)

#  ii. y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3, ]

import numpy as np

y = np.array([1, 1, 1, 2, 3, 4, 2, 4, 3, 3])

frequent_value2 = np.bincount(y).argmax()

index2 = np.where(y == frequent_value2)[0]

print("The most frequent value in the array is: ", frequent_value2)

print("The indices of the most frequent value:", index2)

The most frequent value in the array is:  1
The indices of the most frequent value: [0 5 7 8 9]
The most frequent value in the array is:  1
The indices of the most frequent value: [0 1 2]


In [ ]:
#Q4) For the array gfg = np.matrix('[4, 1, 9; 12, 3, 1; 4, 5, 6]'),
# find i. Sum of all elements

import numpy as np

gfg = np.matrix('[4,1,9;12,3,1;4,5,6]')
print(gfg)
print(np.sum(gfg))

# ii. Sum of all elements row-wise
print(np.sum(gfg,axis=0))

# iii. Sum of all elements column-wise
print(np.sum(gfg,axis=1))

[[ 4  1  9]
 [12  3  1]
 [ 4  5  6]]
45
[[20  9 16]]
[[14]
 [16]
 [15]]


In [ ]:
#Q2) Compare the following numpy arrays: arr1 = np.array([[1, 2], [3, 4]])
#  arr2 = np.array([[1, 2], [3, 4]])
import numpy as np
arr1 = np.array([[1,2],[3,4]])
arr2 = np.array([[1,2],[3,4]])
print(np.equal(arr1,arr2))


[[ True  True]
 [ True  True]]
